In [2]:
import pandas as pd

1- Create the following DataFrame and store it in a variable called df


```
students = {
    "Name": ["Ali", "Sara", "Omar", "Lina", "Youssef", "Mariam"],
    "Age": [20, 21, 19, 22, 20, 21],
    "Grade": [85, 92, 78, 95, 88, 73],
    "Department": ["CS", "AI", "CS", "DS", "AI", "DS"]
}
```

In [100]:
students = {
    "Name": ["Ali", "Sara", "Omar", "Lina", "Youssef", "Mariam"],
    "Age": [20, 21, 19, 22, 20, 21],
    "Grade": [85, 92, 78, 95, 88, 73],
    "Department": ["CS", "AI", "CS", "DS", "AI", "DS"]
}

df = pd.DataFrame(students)
df

      Name  Age  Grade Department
0      Ali   20     85         CS
1     Sara   21     92         AI
2     Omar   19     78         CS
3     Lina   22     95         DS
4  Youssef   20     88         AI
5   Mariam   21     73         DS

---
2- Display:

- First 3 rows  
- Last 2 rows  
- Shape of the DataFrame  
- Column names  
- Data types of each column  

Also explain the difference between:

- `shape`
- `size`
- `len(df)`

with words and examples.

In [101]:
print(df.head(3))

print('##############################################')

print(df.tail(2))

print('##############################################')

print(df.shape)

print('##############################################')

print(df.columns)

print('##############################################')

print(df.dtypes)

#shape -> Gives (number of rows, number of columns) -> EX : (5,3)

#size -> Gives the whole number of elments (size = number of rows *  number of columns) -> EX : 15

#len() -> Gives the number of rows only -> EX : 5

   Name  Age  Grade Department
0   Ali   20     85         CS
1  Sara   21     92         AI
2  Omar   19     78         CS
##############################################
      Name  Age  Grade Department
4  Youssef   20     88         AI
5   Mariam   21     73         DS
##############################################
(6, 4)
##############################################
Index(['Name', 'Age', 'Grade', 'Department'], dtype='object')
##############################################
Name          object
Age            int64
Grade          int64
Department    object
dtype: object

---
3- Select and print:

- The `Name` column only  
- The `Name` and `Grade` columns together  
- The first 2 rows  
- The `Grade` column for the first 3 students  
- All students whose grade is greater than 85  
- All students from the AI department

In [102]:
print(df.loc[:,'Name'])

print('##############################################')

print(df.loc[ : , ['Name','Grade'] ])

print('##############################################')

print(df.loc[ :1 ,:])

print('##############################################')

print(df.loc[ :2 , 'Grade'])

print('##############################################')

print(df[df['Grade']>85])

print('##############################################')

print(df[df['Department'] == 'AI'])

0        Ali
1       Sara
2       Omar
3       Lina
4    Youssef
5     Mariam
Name: Name, dtype: object
##############################################
      Name  Grade
0      Ali     85
1     Sara     92
2     Omar     78
3     Lina     95
4  Youssef     88
5   Mariam     73
##############################################
   Name  Age  Grade Department
0   Ali   20     85         CS
1  Sara   21     92         AI
##############################################
0    85
1    92
2    78
Name: Grade, dtype: int64
##############################################
      Name  Age  Grade Department
1     Sara   21     92         AI
3     Lina   22     95         DS
4  Youssef   20     88         AI
##############################################
      Name  Age  Grade Department
1     Sara   21     92         AI
4  Youssef   20     88         AI

---
4- Add the following columns:

a. `Passed`

Rules:
- Grade >= 60 → `"Yes"`
- Otherwise → `"No"`

b. `Grade_Level`

Rules:
- Grade >= 90 → `"Excellent"`
- Grade >= 80 → `"Good"`
- Otherwise → `"Average"`

Then change the department of `"Omar"` from `"CS"` to `"AI"` without recreating the DataFrame.

In [103]:
def passed(grade):
  if grade >= 60:
    return 'Yes'
  else:
    return 'No'

def grade_level(grade):
  if grade >= 90:
    return 'Excellent'
  elif grade >= 80:
    return 'Good'
  else:
    return 'Average'

df['Passed'] = df['Grade'].apply(passed)

df['Grade_Level'] = df['Grade'].apply(grade_level)

df.loc[df['Name'] == 'Omar' , 'Department'] = 'AI'

df

      Name  Age  Grade Department Passed Grade_Level
0      Ali   20     85         CS    Yes        Good
1     Sara   21     92         AI    Yes   Excellent
2     Omar   19     78         AI    Yes     Average
3     Lina   22     95         DS    Yes   Excellent
4  Youssef   20     88         AI    Yes        Good
5   Mariam   21     73         DS    Yes     Average

---
5- Find:

- Average grade  
- Highest grade  
- Lowest grade  
- Student with the highest grade  
- Average age of students in each department  
- Number of students in each department

In [50]:
print(df['Grade'].mean())

print('##############################################')

print(df['Grade'].max())

print('##############################################')

print(df['Grade'].min())

print('##############################################')

print(df[df['Grade'] == df['Grade'].max()])

print('##############################################')

print(df.groupby('Department')['Age'].mean())

print('##############################################')

print(df.groupby('Department')['Name'].count())

85.16666666666667
##############################################
95
##############################################
73
##############################################
   Name  Age  Grade Department Passed Grade_Level
3  Lina   22     95         DS    Yes   Excellent
##############################################
Department
AI    20.0
CS    20.0
DS    21.5
Name: Age, dtype: float64
##############################################
Department
AI    3
CS    1
DS    2
Name: Name, dtype: int64

---
6- Create a new DataFrame that contains only:

- Students with grade greater than 80  
- Sorted by grade descending  
- Showing only:
  - Name
  - Grade
  - Department

Store the result in a new variable.

In [104]:
df2 = df[df['Grade'] > 80]

df2 = df2.sort_values(by ='Grade' , ascending = False)

df2 = df2.loc[: , ['Name' , 'Grade' , 'Department']]

df2

      Name  Grade Department
3     Lina     95         DS
1     Sara     92         AI
4  Youssef     88         AI
0      Ali     85         CS

---
7- Create the following DataFrame and store it in `df_missing`


```
data = {
    "Name": ["Ali", "Sara", None, "Lina"],
    "Age": [20, None, 19, 22],
    "Grade": [85, 92, 78, None]
}
```

Then:

- Display missing values in each column  
- Display total missing values  
- Fill missing names with `"Unknown"`  
- Fill numeric missing values with the column average

In [105]:
data = {
    "Name": ["Ali", "Sara", None, "Lina"],
    "Age": [20, None, 19, 22],
    "Grade": [85, 92, 78, None]
}

df_missing = pd.DataFrame(data)

print(df_missing.isnull())

print('##############################################')

print(df_missing.isnull().sum())

print('##############################################')

df_missing['Name'] = df_missing['Name'].fillna('Unknown')

df_missing['Age'] = df_missing['Age'].fillna(df_missing['Age'].mean())

df_missing['Grade'] = df_missing['Grade'].fillna(df_missing['Grade'].mean())

df_missing

    Name    Age  Grade
0  False  False  False
1  False   True  False
2   True  False  False
3  False  False   True
##############################################
Name     1
Age      1
Grade    1
dtype: int64
##############################################

      Name        Age  Grade
0      Ali  20.000000   85.0
1     Sara  20.333333   92.0
2  Unknown  19.000000   78.0
3     Lina  22.000000   85.0

---
8- Create the following DataFrames:


```
students_info = pd.DataFrame({
    "ID": [1, 2, 3, 4],
    "Name": ["Ali", "Sara", "Omar", "Lina"],
    "Department": ["CS", "AI", "CS", "DS"]
})

students_grades = pd.DataFrame({
    "ID": [1, 2, 3, 4],
    "Grade": [85, 92, 78, 95]
})
```
Combine both DataFrames into one DataFrame using the `ID` column.

In [106]:
students_info = pd.DataFrame({
    "ID": [1, 2, 3, 4],
    "Name": ["Ali", "Sara", "Omar", "Lina"],
    "Department": ["CS", "AI", "CS", "DS"]
})

students_grades = pd.DataFrame({
    "ID": [1, 2, 3, 4],
    "Grade": [85, 92, 78, 95]
})

students_DataFrame = pd.merge(students_info , students_grades , how = 'outer' , on = 'ID')

students_DataFrame

   ID  Name Department  Grade
0   1   Ali         CS     85
1   2  Sara         AI     92
2   3  Omar         CS     78
3   4  Lina         DS     95

---
9- Create the following DataFrame:


```
new_students = pd.DataFrame({
    "ID": [5, 6],
    "Name": ["Youssef", "Mariam"],
    "Department": ["AI", "DS"]
})
```
Add the new students to the original students DataFrame.

In [107]:
new_students = pd.DataFrame({
    "ID": [5, 6],
    "Name": ["Youssef", "Mariam"],
    "Department": ["AI", "DS"],
    "Grade" : [88, 73]
})

students_DataFrame = pd.concat([students_DataFrame , new_students])

students_DataFrame

   ID     Name Department  Grade
0   1      Ali         CS     85
1   2     Sara         AI     92
2   3     Omar         CS     78
3   4     Lina         DS     95
0   5  Youssef         AI     88
1   6   Mariam         DS     73

---
10- Using the students DataFrame:
- Find the average grade for each department  
- Find the department with the highest average grade

In [108]:
print(students_DataFrame.groupby('Department')['Grade'].mean())

print('##############################################')

print(students_DataFrame.groupby('Department')['Grade'].mean().idxmax())

Department
AI    90.0
CS    81.5
DS    84.0
Name: Grade, dtype: float64
##############################################
AI

---
11- Save the final DataFrame as a CSV file.

In [109]:
students_DataFrame.to_csv('students_DataFrame.csv')